version: 2.1

commands:
  aws-config:
    description: "create credentials file for aws"
    steps:
      - run:
          name: Create credentials file for aws
          command: |
            mkdir ~/.aws
            echo [default] >> ~/.aws/credentials
            echo aws_secret_access_key = $AWS_SECRET_ACCESS_KEY  >> ~/.aws/credentials
            echo aws_access_key_id = $AWS_ACCESS_KEY_ID  >> ~/.aws/credentials
            echo source_profile = default  >> ~/.aws/credentials
            echo region = $AWS_DEFAULT_REGION  >> ~/.aws/credentials

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore src/estate-cloud-contacts-service/estate-cloud-contacts-service.csproj
      - run:
          name: Build
          command: dotnet build src/estate-cloud-contacts-service/estate-cloud-contacts-service.csproj --configuration $BUILD_CONFIGURATION
      - run:
          name: Test
          command: dotnet test test/estate-cloud-contacts-service.Tests/estate-cloud-contacts-service.Tests.csproj --configuration $BUILD_CONFIGURATION --logger:trx --results-directory ~/project/test-results
      - run:
          name: Convert Test Results
          when: always
          command: |
            dotnet tool install -g trx2junit
            export PATH="$PATH:/root/.dotnet/tools"
            trx2junit ~/project/test-results/*.trx
      - store_test_results:
          path: test-results
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y zip
      - sonarcloud/scan
      - run:
          name: Generate Lambda Package
          command: |
            dotnet tool install -g Amazon.Lambda.Tools
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet lambda package --project-location src/estate-cloud-contacts-service --configuration $BUILD_CONFIGURATION --framework netcoreapp2.1 --output-package ~/project/artifacts/deploy-package.zip
      - store_artifacts:
          path: ~/project/artifacts
          destination: .
      - persist_to_workspace:
          root: src
          paths:
            - estate-cloud-contacts-service

  deploy:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
    steps:
      - attach_workspace:
          at: src
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y zip
      - run:
          name: Install Lambda Tools
          command: |
            dotnet tool install -g Amazon.Lambda.Tools
            echo 'export PATH="$PATH:/root/.dotnet/tools"' >> $BASH_ENV
      - aws-config
      - run:
          name: Deploy Stack to AWS
          command: dotnet lambda deploy-serverless --project-location src/estate-cloud-contacts-service --stackname estate-cloud-contacts-service --profile personal --region $AWS_DEFAULT_REGION --s3-bucket $AWS_ARTIFACT_BUCKET

orbs:
  slack: circleci/slack@3.4.2
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  build-and-deploy:
    jobs:
      - build:
          context: SonarCloud
      - slack/approval-notification:
          message: Pending approval
          webhook: $IWT_SMARTA_DEVOPS_WEBHOOK
          requires:
            - build
          filters:
            branches:
              only: master
      - approve-deploy:
          type: approval
          requires:
            - slack/approval-notification
      - deploy:
          requires:
            - approve-deploy
